name: flutter_trip
description: A new Flutter application.

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # banner
  flutter_swiper: ^1.1.6
  # http
  http: ^0.12.2
  # webview
  webview_flutter: ^2.0.8
#  flutter_webview_plugin: ^0.4.0
  # 瀑布流
  flutter_staggered_grid_view: ^0.3.4
  # 启动白屏
  #  flutter_splash_screen: ^0.3.0
  #  flare_splash_screen: ^4.0.0
  # taost
#  fluttertoast: ^8.0.9
  # placeholder
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/type_channelgroup.png
    - images/type_channelgs.png
    - images/type_channelplane.png
    - images/type_channeltrain.png
    - images/type_cruise.png
    - images/type_district.png
    - images/type_food.png
    - images/type_hotel.png
    - images/type_huodong.png
    - images/type_shop.png
    - images/type_sight.png
    - images/type_ticket.png
    - images/type_travelgroup.png
